image: Visual Studio 2019
configuration: Release

environment:
  matrix:
  - solution: PowerToys.sln
  - solution: installer/PowerToysSetup.sln

install:
 - choco install wixtoolset

build_script:
  - msbuild %solution%

artifacts:
    - path: x64\Release\*.*
    - path: installer\PowerToysSetup\x64\Release\*.*
